version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11

executors:
  my-executor:
    docker:
      - image: circleci/node:12.9.1

    working_directory: ~/repo

jobs:
  install-dependencies-and-test:
    docker:
      - image: cypress/base:8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Run tests
          command: |
            export REACT_APP_ENV=dev
            export REACT_APP_HN_API_URL=http://localhost:8080
            export PATH=$PATH:~/repo/node_modules/.bin
            npm run cypress

      - persist_to_workspace:
          root: ~/repo
          paths: .

  build-deploy-staging:
    executor: my-executor

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: build
          command: |
            export REACT_APP_ENV=staging
            export REACT_APP_HN_API_URL=${REACT_APP_HN_API_URL_STAGING}
            export REACT_APP_JIGSAW_DOCUMENT_API_URL=${REACT_APP_JIGSAW_DOCUMENT_API_URL_STAGING}
            npm run build

      - aws-s3/sync:
          from: build
          to: 's3://staging.singleview.hackney.gov.uk/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true

  build-deploy-production:
    executor: my-executor

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: build
          command: |
            export REACT_APP_ENV=production
            export REACT_APP_HN_API_URL=${REACT_APP_HN_API_URL_PRODUCTION}
            export REACT_APP_JIGSAW_DOCUMENT_API_URL=${REACT_APP_JIGSAW_DOCUMENT_API_URL_PRODUCTION}
            npm run build

      - aws-s3/sync:
          from: build
          to: 's3://beta.singleview.hackney.gov.uk/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true

workflows:
  version: 2
  continuous-delivery:
    jobs:
      - install-dependencies-and-test
      - build-deploy-staging:
          requires:
            - install-dependencies-and-test
          filters:
            branches:
              only:
                - master
      - permit-deploy-production:
          type: approval
          requires:
            - build-deploy-staging
      - build-deploy-production:
          requires:
            - permit-deploy-production
